version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8
    container_name: sb_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_db
    volumes:
      - mysql-data:/var/lib/mysql
    # ports:
    #   - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s

  # Spring Boot Backend
  backend:
    build:
      context: ./E_ThreeTierReact
      dockerfile: Dockerfile
    container_name: auth_backend_cont
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: auth_frontend_cont
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

# Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  mysql-data:
    driver: local